import { useState } from 'react'
import { api } from '../services/http'
import type { LabTest } from '../types/api'
import { EmptyState, Feedback, SectionHeading } from './Ui'

type TestForm = { code: string; name: string; description: string; price: string; isActive: boolean }
const blankForm: TestForm = { code: '', name: '', description: '', price: '0', isActive: true }

function toForm(test: LabTest): TestForm { return { code: test.code, name: test.name, description: test.description ?? '', price: String(test.price), isActive: test.isActive } }

export function LabTestPanel({ tests, onChanged }: { tests: LabTest[]; onChanged: () => Promise<void> }) {
  const [form, setForm] = useState<TestForm>(blankForm); const [editingId, setEditingId] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const update = (field: keyof TestForm, value: string | boolean) => setForm((current) => ({ ...current, [field]: value })); const reset = () => { setForm(blankForm); setEditingId(null); setError(null) }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.code || !form.name || !form.price || Number(form.price) < 0) { setError('Completa código, nombre y un precio válido.'); return }; setBusy(true); setError(null); try { const body = { ...form, price: Number(form.price), description: form.description || null }; if (editingId) await api.tests.update(editingId, body); else await api.tests.create(body); reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo guardar la prueba.') } finally { setBusy(false) } }
  async function remove(test: LabTest) { if (!window.confirm(`¿Eliminar la prueba ${test.name}?`)) return; setBusy(true); setError(null); try { await api.tests.remove(test.id); if (editingId === test.id) reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo eliminar la prueba.') } finally { setBusy(false) } }
  return <section className="workspace-section"><SectionHeading eyebrow="Catálogo" title="Pruebas clínicas" description="Define las pruebas disponibles y su precio de referencia." action={<button className="button button-primary" onClick={reset}>+ Nueva prueba</button>} /><div className="content-grid"><form className="form-card" onSubmit={submit}><div className="form-card-heading"><h3>{editingId ? 'Editar prueba' : 'Nueva prueba'}</h3><span>{editingId ? `ID #${editingId}` : 'Catálogo'}</span></div><div className="form-grid"><label>Código<input value={form.code} onChange={(event) => update('code', event.target.value)} /></label><label>Nombre<input value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label className="full-width">Descripción<textarea rows={3} value={form.description} onChange={(event) => update('description', event.target.value)} /></label><label>Precio<input type="number" min="0" step="0.01" value={form.price} onChange={(event) => update('price', event.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={form.isActive} onChange={(event) => update('isActive', event.target.checked)} /> Disponible para nuevas órdenes</label></div><Feedback message={error} /><div className="form-actions"><button className="button button-primary" disabled={busy}>{busy ? 'Guardando...' : editingId ? 'Guardar cambios' : 'Crear prueba'}</button>{editingId && <button type="button" className="button button-quiet" onClick={reset}>Cancelar</button>}</div></form><div className="table-card"><div className="table-card-heading"><h3>Pruebas disponibles</h3><span>{tests.length} registros</span></div>{tests.length === 0 ? <EmptyState message="Todavía no hay pruebas registradas." /> : <div className="table-scroll"><table><thead><tr><th>Prueba</th><th>Precio</th><th>Estado</th><th aria-label="Acciones" /></tr></thead><tbody>{tests.map((test) => <tr key={test.id}><td><strong>{test.name}</strong><small>{test.code}</small></td><td>${Number(test.price).toFixed(2)}</td><td><span className={`pill ${test.isActive ? 'pill-success' : 'pill-muted'}`}>{test.isActive ? 'Activa' : 'Inactiva'}</span></td><td className="row-actions"><button className="text-button" onClick={() => { setEditingId(test.id); setForm(toForm(test)); setError(null) }}>Editar</button><button className="text-button danger" onClick={() => void remove(test)}>Eliminar</button></td></tr>)}</tbody></table></div>}</div></div></section>
}