import { useState } from 'react'
import { api } from '../services/http'
import type { LabOrder, LabTest, Patient } from '../types/api'
import { EmptyState, Feedback, SectionHeading } from './Ui'

type OrderForm = { patientId: string; labTestId: string; statusCode: string }
const blankForm: OrderForm = { patientId: '', labTestId: '', statusCode: 'PENDING' }
const statuses = [{ code: 'PENDING', label: 'Pendiente' }, { code: 'IN_PROGRESS', label: 'En proceso' }, { code: 'COMPLETED', label: 'Completada' }, { code: 'CANCELLED', label: 'Cancelada' }]

export function OrderPanel({ orders, patients, tests, onChanged }: { orders: LabOrder[]; patients: Patient[]; tests: LabTest[]; onChanged: () => Promise<void> }) {
  const [form, setForm] = useState<OrderForm>(blankForm); const [editingId, setEditingId] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const update = (field: keyof OrderForm, value: string) => setForm((current) => ({ ...current, [field]: value })); const reset = () => { setForm(blankForm); setEditingId(null); setError(null) }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.patientId || !form.labTestId) { setError('Selecciona un paciente y una prueba.'); return }; setBusy(true); setError(null); try { const body = { patientId: Number(form.patientId), labTestId: Number(form.labTestId), statusCode: form.statusCode }; if (editingId) await api.orders.update(editingId, body); else await api.orders.create(body); reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo guardar la orden.') } finally { setBusy(false) } }
  async function remove(order: LabOrder) { if (!window.confirm(`¿Eliminar la orden #${order.id}?`)) return; setBusy(true); setError(null); try { await api.orders.remove(order.id); if (editingId === order.id) reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo eliminar la orden.') } finally { setBusy(false) } }
  return <section className="workspace-section"><SectionHeading eyebrow="Órdenes" title="Solicitudes de laboratorio" description="Relaciona un paciente con una prueba y controla su estado." action={<button className="button button-primary" onClick={reset}>+ Nueva orden</button>} /><div className="content-grid"><form className="form-card" onSubmit={submit}><div className="form-card-heading"><h3>{editingId ? 'Editar orden' : 'Nueva orden'}</h3><span>{editingId ? `ID #${editingId}` : 'Solicitud'}</span></div><div className="form-grid"><label className="full-width">Paciente<select value={form.patientId} onChange={(event) => update('patientId', event.target.value)}><option value="">Selecciona un paciente</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.firstName} {patient.lastName} · {patient.documentId}</option>)}</select></label><label className="full-width">Prueba<select value={form.labTestId} onChange={(event) => update('labTestId', event.target.value)}><option value="">Selecciona una prueba</option>{tests.filter((test) => test.isActive).map((test) => <option key={test.id} value={test.id}>{test.name} · {test.code}</option>)}</select></label><label>Estado<select value={form.statusCode} onChange={(event) => update('statusCode', event.target.value)}>{statuses.map((status) => <option key={status.code} value={status.code}>{status.label}</option>)}</select></label></div><Feedback message={error} /><div className="form-actions"><button className="button button-primary" disabled={busy}>{busy ? 'Guardando...' : editingId ? 'Guardar cambios' : 'Crear orden'}</button>{editingId && <button type="button" className="button button-quiet" onClick={reset}>Cancelar</button>}</div></form><div className="table-card"><div className="table-card-heading"><h3>Órdenes registradas</h3><span>{orders.length} registros</span></div>{orders.length === 0 ? <EmptyState message="Todavía no hay órdenes registradas." /> : <div className="table-scroll"><table><thead><tr><th>Paciente</th><th>Prueba</th><th>Estado</th><th>Resultado</th><th aria-label="Acciones" /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.patient.firstName} {order.patient.lastName}</strong><small>Orden #{order.id}</small></td><td><strong>{order.labTest.name}</strong><small>{order.labTest.code}</small></td><td><span className={`pill pill-${order.statusCode.toLowerCase()}`}>{order.status.label}</span></td><td>{order.result ? <span className="result-available">Disponible</span> : <span className="muted-text">Pendiente</span>}</td><td className="row-actions"><button className="text-button" onClick={() => { setEditingId(order.id); setForm({ patientId: String(order.patientId), labTestId: String(order.labTestId), statusCode: order.statusCode }); setError(null) }}>Editar</button><button className="text-button danger" onClick={() => void remove(order)}>Eliminar</button></td></tr>)}</tbody></table></div>}</div></div></section>
}