import { useState } from 'react'
import { api } from '../services/http'
import type { LabOrder, LabResult } from '../types/api'
import { EmptyState, Feedback, SectionHeading } from './Ui'

type ResultForm = { labOrderId: string; value: string; unit: string; referenceRange: string; notes: string }
const blankForm: ResultForm = { labOrderId: '', value: '', unit: '', referenceRange: '', notes: '' }

function toForm(result: LabResult): ResultForm { return { labOrderId: String(result.labOrderId), value: result.value, unit: result.unit ?? '', referenceRange: result.referenceRange ?? '', notes: result.notes ?? '' } }

export function ResultPanel({ results, orders, onChanged }: { results: LabResult[]; orders: LabOrder[]; onChanged: () => Promise<void> }) {
  const [form, setForm] = useState<ResultForm>(blankForm); const [editingId, setEditingId] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const update = (field: keyof ResultForm, value: string) => setForm((current) => ({ ...current, [field]: value })); const reset = () => { setForm(blankForm); setEditingId(null); setError(null) }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.labOrderId || !form.value) { setError('Selecciona una orden y escribe el valor del resultado.'); return }; setBusy(true); setError(null); try { const body = { labOrderId: Number(form.labOrderId), value: form.value, unit: form.unit || null, referenceRange: form.referenceRange || null, notes: form.notes || null }; if (editingId) await api.results.update(editingId, body); else await api.results.create(body); reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo guardar el resultado.') } finally { setBusy(false) } }
  async function remove(result: LabResult) { if (!window.confirm(`¿Eliminar el resultado #${result.id}?`)) return; setBusy(true); setError(null); try { await api.results.remove(result.id); if (editingId === result.id) reset(); await onChanged() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo eliminar el resultado.') } finally { setBusy(false) } }
  const availableOrders = orders.filter((order) => !order.result || order.result.id === editingId)
  return <section className="workspace-section"><SectionHeading eyebrow="Resultados" title="Resultados reportados" description="Registra el valor obtenido para cada orden procesada." action={<button className="button button-primary" onClick={reset}>+ Nuevo resultado</button>} /><div className="content-grid"><form className="form-card" onSubmit={submit}><div className="form-card-heading"><h3>{editingId ? 'Editar resultado' : 'Nuevo resultado'}</h3><span>{editingId ? `ID #${editingId}` : 'Informe'}</span></div><div className="form-grid"><label className="full-width">Orden<select value={form.labOrderId} onChange={(event) => update('labOrderId', event.target.value)} disabled={Boolean(editingId)}><option value="">Selecciona una orden</option>{availableOrders.map((order) => <option key={order.id} value={order.id}>Orden #{order.id} · {order.patient.firstName} {order.patient.lastName} · {order.labTest.name}</option>)}</select></label><label>Valor<input value={form.value} onChange={(event) => update('value', event.target.value)} /></label><label>Unidad<input value={form.unit} onChange={(event) => update('unit', event.target.value)} placeholder="mg/dL" /></label><label>Rango de referencia<input value={form.referenceRange} onChange={(event) => update('referenceRange', event.target.value)} /></label><label className="full-width">Notas<textarea rows={3} value={form.notes} onChange={(event) => update('notes', event.target.value)} /></label></div><Feedback message={error} /><div className="form-actions"><button className="button button-primary" disabled={busy}>{busy ? 'Guardando...' : editingId ? 'Guardar cambios' : 'Crear resultado'}</button>{editingId && <button type="button" className="button button-quiet" onClick={reset}>Cancelar</button>}</div></form><div className="table-card"><div className="table-card-heading"><h3>Resultados registrados</h3><span>{results.length} registros</span></div>{results.length === 0 ? <EmptyState message="Todavía no hay resultados registrados." /> : <div className="table-scroll"><table><thead><tr><th>Orden</th><th>Resultado</th><th>Reporte</th><th aria-label="Acciones" /></tr></thead><tbody>{results.map((result) => <tr key={result.id}><td><strong>Orden #{result.labOrderId}</strong><small>Resultado #{result.id}</small></td><td><strong>{result.value}</strong><small>{result.unit || 'Sin unidad'}{result.referenceRange ? ` · Ref. ${result.referenceRange}` : ''}</small></td><td><small>{result.notes || 'Sin notas'}</small></td><td className="row-actions"><button className="text-button" onClick={() => { setEditingId(result.id); setForm(toForm(result)); setError(null) }}>Editar</button><button className="text-button danger" onClick={() => void remove(result)}>Eliminar</button></td></tr>)}</tbody></table></div>}</div></div></section>
}